language: python

python: 3.6

services: cassandra

sudo: false

env:
  matrix:
    - TOXENV=py27
    - TOXENV=py36
    - TOXENV=coverage
    - TOXENV=py27 CASSANDRA=3.11.1
    - TOXENV=py36 CASSANDRA=3.11.1

cache:
  directories:
    - $HOME/.cache/pip

before_install:
  # Increase stack-size: http://stackoverflow.com/questions/11901421/cannot-start-cassandra-db-using-bin-cassandra
  - '[ "$CASSANDRA" != "" ] && wget http://archive.apache.org/dist/cassandra/${CASSANDRA}/apache-cassandra-${CASSANDRA}-bin.tar.gz && tar -xvzf apache-cassandra-${CASSANDRA}-bin.tar.gz && export CASSANDRA_HOME=`pwd`/apache-cassandra-${CASSANDRA} || true'

install: pip install docutils tox
script: tox
