language: python

python: 3.6

sudo: required

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
      services: cassandra
    - python: 3.5
      env: TOXENV=py35
      services: cassandra
    - python: 3.6
      env: TOXENV=py36
      services: cassandra
    - env: TOXENV=coverage
    - env: TOXENV=py36 CASSANDRA=3.11.1

cache:
  directories:
    - $HOME/.cache/pip

before_install:
  # Increase stack-size: http://stackoverflow.com/questions/11901421/cannot-start-cassandra-db-using-bin-cassandra
  - '[ "$CASSANDRA" != "" ] && wget http://archive.apache.org/dist/cassandra/${CASSANDRA}/apache-cassandra-${CASSANDRA}-bin.tar.gz && tar -xvzf apache-cassandra-${CASSANDRA}-bin.tar.gz && export CASSANDRA_HOME=`pwd`/apache-cassandra-${CASSANDRA} || true'
  - export MAX_HEAP_SIZE='1G'
  - export HEAP_NEWSIZE='200M'

install: pip install docutils tox
script: tox
